/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankRouteImport } from './routes/rank'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as TopicsSubjectRouteImport } from './routes/topics.$subject'
import { Route as ResultsSessionIdRouteImport } from './routes/results.$sessionId'
import { Route as PdfQuizRouteImport } from './routes/pdf.quiz'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as QuizSubjectTopicRouteImport } from './routes/quiz.$subject.$topic'
import { Route as ChatSubjectTopicRouteImport } from './routes/chat.$subject.$topic'

const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSubjectRoute = TopicsSubjectRouteImport.update({
  id: '/topics/$subject',
  path: '/topics/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfQuizRoute = PdfQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => PdfRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubjectTopicRoute = QuizSubjectTopicRouteImport.update({
  id: '/quiz/$subject/$topic',
  path: '/quiz/$subject/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSubjectTopicRoute = ChatSubjectTopicRouteImport.update({
  id: '/chat/$subject/$topic',
  path: '/chat/$subject/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pdf': typeof PdfRouteWithChildren
  '/progress': typeof ProgressRoute
  '/rank': typeof RankRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/pdf/quiz': typeof PdfQuizRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/topics/$subject': typeof TopicsSubjectRoute
  '/chat/': typeof ChatIndexRoute
  '/chat/$subject/$topic': typeof ChatSubjectTopicRoute
  '/quiz/$subject/$topic': typeof QuizSubjectTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pdf': typeof PdfRouteWithChildren
  '/progress': typeof ProgressRoute
  '/rank': typeof RankRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/pdf/quiz': typeof PdfQuizRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/topics/$subject': typeof TopicsSubjectRoute
  '/chat': typeof ChatIndexRoute
  '/chat/$subject/$topic': typeof ChatSubjectTopicRoute
  '/quiz/$subject/$topic': typeof QuizSubjectTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pdf': typeof PdfRouteWithChildren
  '/progress': typeof ProgressRoute
  '/rank': typeof RankRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/pdf/quiz': typeof PdfQuizRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/topics/$subject': typeof TopicsSubjectRoute
  '/chat/': typeof ChatIndexRoute
  '/chat/$subject/$topic': typeof ChatSubjectTopicRoute
  '/quiz/$subject/$topic': typeof QuizSubjectTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pdf'
    | '/progress'
    | '/rank'
    | '/api/chat'
    | '/chat/$threadId'
    | '/pdf/quiz'
    | '/results/$sessionId'
    | '/topics/$subject'
    | '/chat/'
    | '/chat/$subject/$topic'
    | '/quiz/$subject/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pdf'
    | '/progress'
    | '/rank'
    | '/api/chat'
    | '/chat/$threadId'
    | '/pdf/quiz'
    | '/results/$sessionId'
    | '/topics/$subject'
    | '/chat'
    | '/chat/$subject/$topic'
    | '/quiz/$subject/$topic'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pdf'
    | '/progress'
    | '/rank'
    | '/api/chat'
    | '/chat/$threadId'
    | '/pdf/quiz'
    | '/results/$sessionId'
    | '/topics/$subject'
    | '/chat/'
    | '/chat/$subject/$topic'
    | '/quiz/$subject/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PdfRoute: typeof PdfRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  RankRoute: typeof RankRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
  TopicsSubjectRoute: typeof TopicsSubjectRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatSubjectTopicRoute: typeof ChatSubjectTopicRoute
  QuizSubjectTopicRoute: typeof QuizSubjectTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$subject': {
      id: '/topics/$subject'
      path: '/topics/$subject'
      fullPath: '/topics/$subject'
      preLoaderRoute: typeof TopicsSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/quiz': {
      id: '/pdf/quiz'
      path: '/quiz'
      fullPath: '/pdf/quiz'
      preLoaderRoute: typeof PdfQuizRouteImport
      parentRoute: typeof PdfRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subject/$topic': {
      id: '/quiz/$subject/$topic'
      path: '/quiz/$subject/$topic'
      fullPath: '/quiz/$subject/$topic'
      preLoaderRoute: typeof QuizSubjectTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$subject/$topic': {
      id: '/chat/$subject/$topic'
      path: '/chat/$subject/$topic'
      fullPath: '/chat/$subject/$topic'
      preLoaderRoute: typeof ChatSubjectTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PdfRouteChildren {
  PdfQuizRoute: typeof PdfQuizRoute
}

const PdfRouteChildren: PdfRouteChildren = {
  PdfQuizRoute: PdfQuizRoute,
}

const PdfRouteWithChildren = PdfRoute._addFileChildren(PdfRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PdfRoute: PdfRouteWithChildren,
  ProgressRoute: ProgressRoute,
  RankRoute: RankRoute,
  ApiChatRoute: ApiChatRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
  TopicsSubjectRoute: TopicsSubjectRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatSubjectTopicRoute: ChatSubjectTopicRoute,
  QuizSubjectTopicRoute: QuizSubjectTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
